import { MEDIA } from './media'
import type { Project } from './types'

// Каталог проектов — CONTENT-SPEC §5.2. Цены не хранятся: их считает src/lib/pricing.ts.
// Экспликация: сумма площадей помещений равна площади дома (проверяет unit-тест).
export const PROJECTS: Project[] = [
  {
    slug: 'nordic',
    name: 'NORDIC',
    style: 'minimal',
    area: 290,
    terrace: 68,
    floors: 1,
    bedrooms: 3,
    bathrooms: 3,
    tagline: 'Одноэтажный дом без лестниц: все комнаты на одном уровне, гостиная со вторым светом.',
    features: [
      'Кухня-гостиная со вторым светом и выходом на террасу',
      'Мастер-спальня с гардеробной и своей ванной',
      'Сауна с душевой и постирочная рядом со спальнями',
      'Безбарьерная планировка: без порогов и ступеней',
    ],
    construction: {
      foundation: 'Утеплённая шведская плита с тёплым полом',
      walls: 'Клееный брус из северной ели',
      glazing: 'Двухкамерные энергосберегающие стеклопакеты',
    },
    explication: [
      {
        floor: 'Этаж 1',
        rooms: [
          { name: 'Прихожая', area: 12 },
          { name: 'Гардероб при входе', area: 4 },
          { name: 'Кухня-гостиная', area: 78 },
          { name: 'Кладовая', area: 5 },
          { name: 'Мастер-спальня', area: 28 },
          { name: 'Гардеробная', area: 9 },
          { name: 'Ванная при мастер-спальне', area: 10 },
          { name: 'Спальня', area: 18 },
          { name: 'Спальня', area: 17 },
          { name: 'Санузел', area: 7 },
          { name: 'Санузел', area: 6 },
          { name: 'Кабинет', area: 15 },
          { name: 'Игровая', area: 20 },
          { name: 'Сауна с душевой', area: 14 },
          { name: 'Постирочная', area: 8 },
          { name: 'Котельная', area: 9 },
          { name: 'Коридор и холл', area: 30 },
        ],
      },
    ],
    cover: MEDIA.nordicExterior,
    gallery: [MEDIA.nordicExterior, MEDIA.nordicInterior, MEDIA.nordicScheme],
  },
  {
    slug: 'vista',
    name: 'VISTA',
    style: 'fachwerk',
    area: 380,
    terrace: 60,
    floors: 2,
    bedrooms: 4,
    bathrooms: 4,
    tagline: 'Фахверковый каркас и остекление в два этажа: гостиная открыта на участок.',
    features: [
      'Гостиная со вторым светом и панорамными окнами в два этажа',
      'Мастер-спальня с гардеробной и ванной',
      'Гостевая спальня с санузлом на первом этаже',
      'Навес на два автомобиля',
    ],
    construction: {
      foundation: 'Монолитная ребристая плита с гидроизоляцией',
      walls: 'Клееный брус 240 × 240 мм',
      glazing: 'Двухкамерные энергосберегающие стеклопакеты в стоечно-ригельной системе',
    },
    explication: [
      {
        floor: 'Этаж 1',
        rooms: [
          { name: 'Прихожая', area: 14 },
          { name: 'Гостиная со вторым светом', area: 64 },
          { name: 'Кухня-столовая', area: 36 },
          { name: 'Кабинет', area: 16 },
          { name: 'Гостевая спальня', area: 18 },
          { name: 'Санузел', area: 6 },
          { name: 'Котельная', area: 9 },
          { name: 'Кладовая', area: 6 },
          { name: 'Холл и лестница', area: 22 },
        ],
      },
      {
        floor: 'Этаж 2',
        rooms: [
          { name: 'Мастер-спальня', area: 34 },
          { name: 'Гардеробная', area: 12 },
          { name: 'Ванная при мастер-спальне', area: 12 },
          { name: 'Спальня', area: 22 },
          { name: 'Спальня', area: 20 },
          { name: 'Санузел', area: 7 },
          { name: 'Санузел', area: 6 },
          { name: 'Семейная гостиная', area: 26 },
          { name: 'Библиотека', area: 14 },
          { name: 'Постирочная', area: 8 },
          { name: 'Холл', area: 28 },
        ],
      },
    ],
    cover: MEDIA.vistaExterior,
    gallery: [MEDIA.vistaExterior, MEDIA.vistaInterior, MEDIA.vistaScheme],
  },
  {
    slug: 'chalet',
    name: 'CHALET',
    style: 'chalet',
    area: 320,
    terrace: 50,
    floors: 1,
    bedrooms: 3,
    bathrooms: 4,
    tagline: 'Каменный цоколь, каминный зал и панорамные фронтоны под широкой кровлей.',
    features: [
      'Каминный зал с панорамным фронтоном',
      'Кухня-столовая с выходом на террасу',
      'Винная комната и кабинет',
      'Три спальни, у каждой свой санузел',
    ],
    construction: {
      foundation: 'Монолитная плита с гранитным цоколем',
      walls: 'Клееный брус 280 мм и лиственница',
      glazing: 'Стоечно-ригельное остекление фронтонов, двухкамерные стеклопакеты',
    },
    explication: [
      {
        floor: 'Этаж 1',
        rooms: [
          { name: 'Прихожая', area: 14 },
          { name: 'Каминный зал', area: 70 },
          { name: 'Кухня-столовая', area: 40 },
          { name: 'Мастер-спальня', area: 30 },
          { name: 'Гардеробная', area: 10 },
          { name: 'Ванная при мастер-спальне', area: 12 },
          { name: 'Спальня', area: 20 },
          { name: 'Санузел', area: 6 },
          { name: 'Спальня', area: 19 },
          { name: 'Санузел', area: 6 },
          { name: 'Гостевой санузел', area: 4 },
          { name: 'Кабинет', area: 16 },
          { name: 'Винная комната', area: 10 },
          { name: 'Котельная', area: 10 },
          { name: 'Кладовая', area: 6 },
          { name: 'Постирочная', area: 8 },
          { name: 'Коридор и холл', area: 39 },
        ],
      },
    ],
    cover: MEDIA.chaletExterior,
    gallery: [MEDIA.chaletExterior, MEDIA.chaletInterior, MEDIA.chaletScheme],
  },
  {
    slug: 'titan',
    name: 'TITAN',
    style: 'monolith',
    area: 540,
    terrace: 120,
    floors: 2,
    bedrooms: 5,
    bathrooms: 6,
    tagline: 'Монолитный каркас с консольными выносами и эксплуатируемой кровлей.',
    features: [
      'Консольные выносы второго этажа над террасой',
      'Эксплуатируемая кровля с видовой площадкой',
      'Гостиная со вторым светом, кабинет и тренажёрный зал',
      'Пять спален, у мастер-спальни — гардеробная и ванная',
    ],
    construction: {
      foundation: 'Сваи с монолитным железобетонным ростверком',
      walls: 'Монолитный железобетонный каркас, фасад из термодревесины',
      glazing: 'Раздвижные панорамные порталы, двухкамерные стеклопакеты',
    },
    explication: [
      {
        floor: 'Этаж 1',
        rooms: [
          { name: 'Прихожая', area: 18 },
          { name: 'Гардероб', area: 6 },
          { name: 'Гостиная со вторым светом', area: 96 },
          { name: 'Кухня-столовая', area: 48 },
          { name: 'Кабинет', area: 22 },
          { name: 'Гостевая спальня', area: 22 },
          { name: 'Санузел при гостевой', area: 7 },
          { name: 'Гостевой санузел', area: 5 },
          { name: 'Тренажёрный зал', area: 30 },
          { name: 'Котельная', area: 14 },
          { name: 'Кладовая', area: 8 },
          { name: 'Постирочная', area: 10 },
          { name: 'Холл и лестница', area: 40 },
        ],
      },
      {
        floor: 'Этаж 2',
        rooms: [
          { name: 'Мастер-спальня', area: 42 },
          { name: 'Гардеробная', area: 18 },
          { name: 'Ванная при мастер-спальне', area: 18 },
          { name: 'Спальня', area: 26 },
          { name: 'Санузел', area: 8 },
          { name: 'Спальня', area: 24 },
          { name: 'Санузел', area: 8 },
          { name: 'Спальня', area: 22 },
          { name: 'Санузел', area: 7 },
          { name: 'Холл', area: 41 },
        ],
      },
    ],
    cover: MEDIA.titanExterior,
    gallery: [MEDIA.titanExterior, MEDIA.titanInterior, MEDIA.titanScheme],
  },
]

export const getProject = (slug: string | null | undefined) => PROJECTS.find((p) => p.slug === slug)
